apps/home/urls.py
from django.urls import path, re_path
from apps.home import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [

    path('', views.index, name='home'),

    path('create-project', views.create_new_project, name='create_project'),

    path('category_form', views.add_category, name='add_category'),

    path('project-details/<int:project_id>', views.show_project_details, name='show_project'),

    path('project-details/<int:project_id>/donate', views.donate, name='donate'),

    path('project-details/<int:project_id>/comment', views.create_comment, name='create_comment'),

    path('project-details/<int:project_id>/cancel', views.cancel_project, name='cancel_project'),

    path('project-details/<int:project_id>/report', views.add_report, name='create_report'),

    path('project-details/<int:comment_id>/report_comment', views.add_comment_report, name='create_comment_report'),

    path('project-details/<int:comment_id>/reply', views.create_comment_reply, name='create_comment_reply'),

    path('projects', views.all_projects, name='all_projects'),

    path('projects/category/<int:category_id>', views.get_category_projects, name='get_category'),

    path('projects/tag/<int:tag_id>', views.get_tag_projects, name='get_tag'),

    path('projects/featured', views.get_featured_projects, name='featured_projects'),

    path('search-result', views.search, name='search-result'),

    path('<int:project_id>/rate', views.rate, name='project_rate'),

    # Matches any html file
    re_path(r'^.*\.*', views.pages, name='pages'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('ResetPasswordLink/<str:uidb64>/<str:token>/', views.reset_password_link, name='ResetPasswordLink'),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name='activate'),
    path('<str:load_template>/', views.pages, name='pages'),
]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this
from django.conf.urls.static import static
from django.conf import settings




urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register
    path("", include("apps.home.urls"))             # UI Kits Html files
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/home/models.py
from django.utils import timezone
from django.db import models
from django.db.models.signals import post_migrate
from django.dispatch import receiver

from django.db import models
from pkg_resources import require
from apps.authentication.models import Register
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=250)
    
    def __str__(self):
        return self.name

@receiver(post_migrate)
def create_default_categories(sender, **kwargs):
    if sender.name == 'home':
        Category = sender.get_model('Category')
        if Category.objects.count() == 0:
            default_categories = [
                'Technology',
                'Art',
                'Music',
                'Film',
                'Games',
                'Publishing',
                'Food',
                'Fashion',
                'Design',
                'Education'
            ]
            for category_name in default_categories:
                Category.objects.get_or_create(name=category_name)


class Tag(models.Model):
    name = models.CharField(max_length=100,null=True, blank=True)

    def __str__(self):
        return self.name


class Project(models.Model):
    title = models.CharField(max_length=100)
    details = models.TextField()
    total_target = models.FloatField()
    start_time = models.DateTimeField(default=timezone.now)
    end_time = models.DateTimeField(default=timezone.now)
    is_featured = models.BooleanField(default=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(Register, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag, blank=True)  # Removed null=True
    created_at = models.DateTimeField(auto_now_add=True)
   

    def __str__(self):
        return self.title
    

class Image(models.Model):
    images = models.ImageField(upload_to="")
    project = models.ForeignKey(Project, on_delete=models.CASCADE, default=None)


class Comment(models.Model):
    comment = models.TextField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(Register, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(f'comment by {self.user.first_name} on {self.project.title} project.')


class Donation(models.Model):
    donation = models.FloatField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(Register, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    

class Project_Report(models.Model):
    REPOT_DATA=[('ip','inappropriate'),('ags','aggressive')]
    report =  models.CharField(
        max_length=200,
        choices=REPOT_DATA,
        default='ip',
    )
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(Register, on_delete=models.CASCADE)


class Comment_Report(models.Model):
    REPOT_DATA=[('ip','inappropriate')]
    report =  models.CharField(
        max_length=200,
        choices=REPOT_DATA,
        default='ip',
    )
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(Register, on_delete=models.CASCADE)


class Reply(models.Model):
    reply = models.CharField(max_length=30)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(Register, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class Rate(models.Model):
    rate = models.IntegerField()
    projcet = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(Register, on_delete=models.CASCADE)

apps/home/views.py
# from asyncio.windows_events import NULL
from django import template
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from django.shortcuts import redirect, render, get_object_or_404
from django.template import loader
from django.urls import reverse
from django.db.models import Avg, Sum
from collections import defaultdict
from datetime import datetime
import re
from apps.home.models import Category, Comment, Donation, Project, Image, Project_Report, Rate, Reply, Tag, Comment_Report
from apps.home.forms import Project_Form, Report_form, Reply_form, Category_form
from django.forms.utils import ErrorList
from apps.authentication.models import Register
from django.template import TemplateDoesNotExist
NULL={}

def getUser(request):
        user = Register.objects.get(id=request.session['user_id'])
        return user
    
def index(request):
    if 'user_id' in request.session:
        user = getUser(request)
    else:
        user = NULL
        
    highest_rated_projects = Project.objects.annotate(
       avg_rate=Avg('rate__rate')).order_by('-avg_rate')[:5]
    last_5_projects = Project.objects.all().order_by('-id')[:5]
    featured_projects = Project.objects.filter(is_featured=1)[:5]

    images = []
    for project in highest_rated_projects:
        images.append(project.image_set.all().first().images.url)

    context = {
        'highest_rated_projects':highest_rated_projects,
        'latest_5_projects': last_5_projects,
        'featured_projects': featured_projects,
        'images': images,
        'projects_count': len(Project.objects.all()),
        'donors_count': len(Donation.objects.all()),
        'reviews_count': len(Rate.objects.all()),
        'user': user
    }
    
    html_template = loader.get_template('home/index.html')
    return HttpResponse(html_template.render(context, request))


def create_new_project(request):
    if 'user_id' not in request.session:
        user = NULL
        return redirect('login')
    else:
        user = getUser(request)
        my_images = Image.objects.all()
        if request.method == 'GET':

            form = Project_Form()
           
            
            return render(request, "home/create-project.html", context={"form": form, 'images': my_images, "user":user})

        if request.method == "POST":
            tag_error=''
                    
            if "tag" in request.POST or request.POST['newTag']!="":
                
                if(request.POST['newTag']!= ''):

                    newTag=re.sub("\s+","_",request.POST['newTag'].strip())
                    new_tag=Tag.objects.create(name=newTag).id
                    request.POST = request.POST.copy()
                    request.POST.update({
	                "tag":new_tag
                    })
            else:
                tag_error="Please add tag"
            
                    
            form = Project_Form(request.POST, request.FILES)
            if tag_error!="":
                
               form.add_error('tag',tag_error)
               
            images = request.FILES.getlist('images')
            if form.is_valid():
                project = form.save(commit=False)
                project.user = user
                project.save()
                form.save_m2m()
                for image in images:
                    Image.objects.create(project_id=project.id, images=image)
                return redirect('home')
        else:
            form = Project_Form()
        return render(request, "home/create-project.html", context={"form": form, "user":user})


def show_project_details(request, project_id):
    if 'user_id' not in request.session:
        user = NULL
    else:
        user = getUser(request)
    try:
        project = Project.objects.get(id=project_id)
        donate = project.donation_set.all().aggregate(Sum("donation"))
        donations_count = len(project.donation_set.all())
        comments = project.comment_set.all()
        replies = Reply.objects.all()
        project_images = project.image_set.all()
        counter=[]
        for image in project_images:
            counter.append("1")
        counter.pop()
        tags = project.tag.all()
        related_projects_tags = []
        for tag in tags:
            related_projects_tags.append(tag.project_set.all())

        related_projects = Project.objects.none().union(*related_projects_tags)[:4]
        related_projects_images = []
        for related_project in related_projects:
            related_projects_images.append(related_project.image_set.all().first().images.url)


        myFormat = "%Y-%m-%d %H:%M:%S"
        today = datetime.strptime(datetime.now().strftime(myFormat), myFormat)
        end_date = datetime.strptime(project.end_time.strftime(myFormat), myFormat)
        days_diff = (end_date-today).days
        
        new_report_form = Report_form()
        reply = Reply_form()

        donation_average = (donate["donation__sum"] if donate["donation__sum"] else 0)*100/project.total_target
        average_rating = project.rate_set.all().aggregate(Avg('rate'))['rate__avg']

        # return user rating if found
        user_rating = 0
        
        if 'user_id' in request.session:
            # prev_rating = Project.rate_set.get(user_id=user.id)
            prev_rating=[]

            if prev_rating:
                user_rating = prev_rating[0].rate

        if average_rating is None:
            average_rating = 0

        context = {
            'project': project,
            'donation': donate["donation__sum"] if donate["donation__sum"] else 0,
            'donations': donations_count,
            'days': days_diff,
            'comments': comments,
            'project_images': project_images,
            'replies': replies,
            'tags': tags,

            'report_form': new_report_form,
            'reply_form': reply,
            'related_projects': related_projects,
            'images': related_projects_images,
            
            'check_target': project.total_target*.25,
            'donation_average': donation_average,

            'rating': average_rating*20,
            'user_rating': user_rating,
            'rating_range': range(5, 0, -1),
            'average_rating': average_rating,
            
            'user':user,
            'counter':counter
            }

        return render(request, "home/project-details.html", context)
    except Project.DoesNotExist:
        html_template = loader.get_template('home/page-404.html')
        return HttpResponse(html_template.render(context, request))
 

def get_tag_projects(request, tag_id):
    if 'user_id' not in request.session:
        user = NULL
    else:
        user = getUser(request)
    context = {}
    try:
        tag = Tag.objects.get(id=tag_id)
        projects = tag.project_set.all()

        donations = []
        progress_values = []
        images = []
        for project in projects:
            donate = project.donation_set.all().aggregate(Sum("donation"))
            total_donation = donate["donation__sum"] if donate["donation__sum"] else 0
            
            progress_values.append(total_donation * 100/project.total_target)
            donations.append(total_donation)
            images.append(project.image_set.all().first().images.url)

        context = {
            'title': tag,
            'projects': projects,
            'images': images,
            'donations': donations,
            'progress_values': progress_values,
            'user':user
        }
        return render(request, "home/tag-projects.html", context)
    except Project.DoesNotExist:
        html_template = loader.get_template('home/page-404.html')
        return HttpResponse(html_template.render(context, request))


def get_category_projects(request, category_id):
    if 'user_id' not in request.session:
        user = NULL
    else:
        user = getUser(request)
    context = {}
    try:
        projects = Project.objects.filter(
            category_id=category_id).all()

        donations = []
        progress_values = []
        images = []
        for project in projects:
            donate = project.donation_set.all().aggregate(Sum("donation"))
            total_donation = donate["donation__sum"] if donate["donation__sum"] else 0
            progress_values.append(total_donation * 100/project.total_target)

            donations.append(total_donation)

            images.append(project.image_set.all().first().images.url)

        title = Category.objects.get(id=category_id)
        context = {
            'title': title,
            'projects': projects,
            'donations': donations,
            'images': images,
            'progress_values': progress_values,
            'user':user
        }
        return render(request, "home/category.html", context)
    except Project.DoesNotExist:
        html_template = loader.get_template('home/page-404.html')
        return HttpResponse(html_template.render(context, request))


def all_projects(request):
    if 'user_id' not in request.session:
        user = NULL
    else:
        user = getUser(request)
    context = {}
    try:
        projects = Project.objects.all()

        donations = []
        progress_values = []
        images = []
        for project in projects:
            donate = project.donation_set.all().aggregate(Sum("donation"))
            total_donation = donate["donation__sum"] if donate["donation__sum"] else 0
            progress_values.append(total_donation * 100/project.total_target)
            donations.append(total_donation)
            images.append(project.image_set.all().first().images.url)

        context = {
            'projects': projects,
            'images': images,
            'title': 'All Projects',
            'donations': donations,
            'progress_values': progress_values,
            'user':user

apps/templates/home/all_projects.html
{% extends 'layouts/projects_template.html' %}

apps/templates/home/category.html
{% extends 'layouts/projects_template.html' %}

{% block project_type %}
Category :
{% endblock project_type %}

apps/templates/home/category_form.html
{% extends 'layouts/base.html' %} {% block title %} Add Category {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %} {% block body_class %}
forms-sections {% endblock body_class %} {% block content %}
{% comment %} {% include "includes/navigation-light.html" %} {% endcomment %}

<div class="container mt-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-lg">
                <div class="card-header">
                    <h3 class="text-center">Add New Category</h3>
                </div>
                <div class="card-body">
                    <form method="post" action="{% url 'add_category' %}" class="text-center" autocomplete="off">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label class="form-label">Category Name</label>
                            {{ form.name }}
                            {% if form.name.errors %}
                                <div class="text-danger">
                                    {{ form.name.errors }}
                                </div>
                            {% endif %}
                        </div>
                        <button type="submit" class="btn bg-gradient-primary">Save Category</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}

<script src="/static/assets/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>

{% endblock javascripts %}

apps/templates/home/create-project.html
{% extends 'layouts/base.html' %}

{% block title %} Create Project {% endblock title %}

{% block content %}
<div class="container">
  <div class="py-5 mx-auto">
    <div class="col-md-8 card d-flex shadow-lg p-4 mt-5 mx-auto">
      <div class="text-center">
        <h3 class="text-gradient text-primary">Create New Project</h3>
      </div>
      <div class="card card-plain">
        <form role="form" id="contact-form" method="post" autocomplete="off" enctype="multipart/form-data">
          {% csrf_token %}

          <div class="mb-3">
            <label class="form-label">Project Title</label>
            {{ form.title }}
          </div>
          <span class="text-error">{{ form.title.errors }}</span>

          <div class="mb-3">
            <label class="form-label">Details</label>
            {{ form.details }}
          </div>
          <span class="text-error">{{ form.details.errors }}</span>

          <div class="mb-3">
            <label class="form-label">Total Target</label>
            {{ form.total_target }}
          </div>
          <span class="text-error">{{ form.total_target.errors }}</span>

          <div class="mb-3">
            <label class="form-label">Start Date & Time</label>
            {{ form.start_time }}
          </div>
          <span class="text-error">{{ form.start_time.errors }}</span>

          <div class="mb-3">
            <label class="form-label">End Date & Time</label>

            {{ form.end_time }}
          </div>
          <span class="text-error">{{ form.end_time.errors }}</span>

          <div class="mb-3">
            <label class="form-label">Category</label>
            <div class="d-flex">
              {{ form.category }}
              <a href="{% url 'add_category' %}" class="btn bg-gradient-primary ms-2">Add New Category</a>
            </div>
          </div>
          <span class="text-error">{{ form.category.errors }}</span>


          <div class="mb-3">
            <label class="form-label">Add tag</label>
            <input type="text" class="inp form-control my-1" maxlength="8" name="newTag" class="form-control"  id="id_tag"/>
            <span class="show_tag " style="padding: 2px;background-color: rgba(145, 9, 120, 0.61);border-radius: 15%; color: rgb(241, 240, 255);"></span>
            <p style="margin: 2px; color: black; font-size: small; font-weight: 550;">or choose one : </p>
            {{ form.tag }}
          </div>
          <span class="text-error">{{ form.tag.errors }}</span>

          <div class="mb-3">
            <label class="form-label">Photos</label><br />
            <input class="form-control" type="file" name="images" multiple required>
          </div>

          <div class="text-center">
            <button type="submit" name="create_project" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">
              Create
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<script>


// let btnAdd = document.querySelector('button');
let input = document.querySelector('.inp');
let show = document.querySelector('.show_tag');

input.addEventListener('keyup', () =>{
    show.innerText = input.value.replace(/\s+/g,'_').trim()

    
  
});
</script>
<style>
  .btn-primary {
    background: #000 !important;
    border: none !important;
  }
  
  .btn-primary:hover {
    background: #333 !important;
  }

  .btn.bg-gradient-primary {
    background: #000 !important;
    border: none !important;
  }

  .btn.bg-gradient-primary:hover {
    background: #333 !important;
  }

  .btn {
    background: #000 !important;
    color: white !important;
  }

  .btn:hover {
    background: #333 !important;
  }
</style>
{% endblock content %}

apps/templates/home/page-403.html
{% extends 'layouts/base.html' %}

{% block title %} Error 403 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} contact-us {% endblock body_class %}

{% block content %}

  {% comment %} {% include "includes/navigation-light.html" %} {% endcomment %}

  <header>
    <div class="page-header section-height-85">
      <div>
        <img class="position-absolute fixed-top ms-auto w-50 h-100 z-index-0 d-none d-sm-none d-md-block border-radius-section border-top-end-radius-0 border-top-start-radius-0 border-bottom-end-radius-0" src="/static/assets/img/curved-images/curved8.jpg">
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-7 d-flex justify-content-center flex-column">
            <div class="card d-flex blur justify-content-center p-4 shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
              <div class="text-center">
                <h3 class="text-gradient text-primary">
                    Error 403
                </h3>
                <p class="mb-0">
                  Access denied. Please contact support or authenticate.
                </p>
              </div>
              <form role="form" id="contact-form" method="post" autocomplete="off">
                  <div class="row">
                    <div class="col-md-12 text-center">
                      <a href="/" class="btn bg-gradient-primary mt-3 mb-0">HOME</a>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}

  <script src="/static/assets/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>

{% endblock javascripts %}

apps/templates/home/page-404.html
{% extends 'layouts/base.html' %}

{% block title %} Error 404 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} contact-us {% endblock body_class %}

{% block content %}

  {% comment %} {% include "includes/navigation-light.html" %} {% endcomment %}

  <header>
    <div class="page-header section-height-85">
      <div>
        <img class="position-absolute fixed-top ms-auto w-50 h-100 z-index-0 d-none d-sm-none d-md-block border-radius-section border-top-end-radius-0 border-top-start-radius-0 border-bottom-end-radius-0" src="/static/assets/img/curved-images/curved8.jpg">
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-7 d-flex justify-content-center flex-column">
            <div class="card d-flex blur justify-content-center p-4 shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
              <div class="text-center">
                <h3 class="text-gradient text-primary">
                    Error 404 
                </h3>
                <p class="mb-0">
                  The page you're looking for doesn't exist.
                </p>
              </div>
              <form role="form" id="contact-form" method="post" autocomplete="off">
                  <div class="row">
                    <div class="col-md-12 text-center">
                      <a href="/" class="btn bg-gradient-primary mt-3 mb-0">HOME</a>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}

  <script src="/static/assets/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>

{% endblock javascripts %}

apps/templates/home/page-500.html
{% extends 'layouts/base.html' %}

{% block title %} Error 500 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} contact-us {% endblock body_class %}

{% block content %}

  <header>
    <div class="page-header section-height-85">
      <div>
        <img class="position-absolute fixed-top ms-auto w-50 h-100 z-index-0 d-none d-sm-none d-md-block border-radius-section border-top-end-radius-0 border-top-start-radius-0 border-bottom-end-radius-0" src="/static/assets/img/curved-images/curved8.jpg">
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-7 d-flex justify-content-center flex-column">
            <div class="card d-flex blur justify-content-center p-4 shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
              <div class="text-center">
                <h3 class="text-gradient text-primary">
                    Error 500
                </h3>
                <p class="mb-0">
                  Server Error. If the problem persists, please contact support.
                </p>
              </div>
              <form role="form" id="contact-form" method="post" autocomplete="off">
                  <div class="row">
                    <div class="col-md-12 text-center">
                      <a href="/" class="btn bg-gradient-primary mt-3 mb-0">HOME</a>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}

  <script src="/static/assets/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>

{% endblock javascripts %}

apps/templates/home/search-result.html
{% extends 'layouts/projects_template.html' %}

{% load index %}

{% block project_type %}
Projects related to your search : <br />
{% endblock project_type %}

{% block extra_content_title %}
Tags related to your search : <br />
{% endblock extra_content_title %}

apps/templates/home/tag-projects.html
{% extends 'layouts/projects_template.html' %}

{% block project_type %}
Tag :
{% endblock project_type %}